version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_report:
    run: python:latest python analysis/report.py output output
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        report: output/descriptives.html

  run_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/Study_Analysis.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        notebook: output/Study_Analysis.html
        csv1: output/PriorityCounts_NoWorkforce.csv
        csv2: output/PriorityCounts_WithWorkforce.csv
        csv3: output/clinExtrVuln_propensity.csv
        csv4: output/atRisk_propensity.csv
        csv5: output/VaccinatedByPriorityByMonth.csv
        csv6: output/VaccinatedByPriorityByMonth_2.csv
        png1: output/waterfall_age.png
        png2: output/waterfall_wf.png
