version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  run_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/Study_Analysis.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        notebook: output/Study_Analysis.html
        csv: output/PriorityCounts_NoWorkforce.csv
        csv: output/PriorityCounts_WithWorkforce.csv
        csv: output/clinExtrVuln_propensity.csv
        csv: output/atRisk_propenstiy.csv
        png: output/waterfall_age.png
        png: output/waterfall_wf.png
