version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  run_notebook:
    run: jupyter:latest jupyter nbconvert /analysis/Study_Analysis.ipynb --execute --to html --output-dir=/output --ExecutePreprocessor.timeout=86400
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        notebook: output/Study_analysis.html
